kind: Service
apiVersion: v1
metadata:
  name: p-service
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
  #type: LoadBalancer
  selector:
    app: pepe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: p-deploy
  namespace: production
spec:
  selector:
    matchLabels:
      app: pepe
  replicas: 2
  template:
    metadata:
      labels:
        app: pepe
    spec:
      containers:
      - name: php-p
        image: farman17/aplikasi-sigaka
        ports:
          - containerPort: 80
       

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: p-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sigaka.dailybugis.my.id
    http:
      paths:
      #- path: /
      - backend:
          serviceName: p-service
          servicePort: 80

